version: '3.8'

services:
  dockerpostgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: testdatabase
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
